# Generated by Django 5.1.3 on 2025-02-26 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='job_company',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
