# Generated by Django 5.1.3 on 2025-03-06 04:42

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_savedjob_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('job_type', models.CharField(choices=[('IN', 'Intern'), ('FT', 'Full-Time'), ('PT', 'Part-Time'), ('TP', 'Temporary'), ('CT', 'Contract')], default='FT', max_length=100)),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['expiry_time'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('api.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_company',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_similarity',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_title',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='status',
            field=models.CharField(choices=[('I', 'In Review'), ('A', 'Accepted'), ('R', 'Rejected')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='api.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruiter'),
        ),
    ]
