/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Seekers see and create their own applications.
         *
         *     Recruiters see applications to jobs they posted, and are the only ones who
         *     can change status. This is the endpoint the old ``recruiter_update_status``
         *     stub was meant to be.
         */
        get: operations["applications_list"];
        put?: never;
        /**
         * @description Seekers see and create their own applications.
         *
         *     Recruiters see applications to jobs they posted, and are the only ones who
         *     can change status. This is the endpoint the old ``recruiter_update_status``
         *     stub was meant to be.
         */
        post: operations["applications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Seekers see and create their own applications.
         *
         *     Recruiters see applications to jobs they posted, and are the only ones who
         *     can change status. This is the endpoint the old ``recruiter_update_status``
         *     stub was meant to be.
         */
        get: operations["applications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Seekers see and create their own applications.
         *
         *     Recruiters see applications to jobs they posted, and are the only ones who
         *     can change status. This is the endpoint the old ``recruiter_update_status``
         *     stub was meant to be.
         */
        patch: operations["applications_partial_update"];
        trace?: never;
    };
    "/api/v1/ats-report/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Score the caller's resume against a pasted job description and return matched skills, weighted gaps, format checks and suggested fixes. */
        post: operations["ats_report_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Exchange credentials for an access/refresh token pair. */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Blacklist a refresh token so it cannot be used again. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read or update the authenticated user's own profile. */
        get: operations["auth_me_retrieve"];
        /** @description Read or update the authenticated user's own profile. */
        put: operations["auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Read or update the authenticated user's own profile. */
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a seeker or recruiter account and return tokens immediately. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness and database connectivity probe. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Open jobs, newest first. */
        get: operations["jobs_list"];
        put?: never;
        post: operations["jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jobs_retrieve"];
        put: operations["jobs_update"];
        post?: never;
        delete: operations["jobs_destroy"];
        options?: never;
        head?: never;
        patch: operations["jobs_partial_update"];
        trace?: never;
    };
    "/api/v1/jobs/{id}/applicants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Applicants for this job. Recruiter-only, own jobs only. */
        get: operations["jobs_applicants_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Rank open jobs against the caller's primary resume. Results are real job postings, scored with explanations of what matched. */
        get: operations["recommendations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resumes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resumes_retrieve"];
        put?: never;
        post?: never;
        delete: operations["resumes_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download a resume. Permitted for its owner, and for recruiters who have received an application including it. */
        get: operations["resumes_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{id}/set-primary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumes_set_primary_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload and parse a resume. Parsing happens once, here, so that scoring requests never re-read the file. */
        post: operations["resumes_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A recruiter's view of an application to one of their jobs. */
        Applicant: {
            readonly id: number;
            readonly job: number;
            readonly job_title: string;
            readonly applicant_name: string;
            readonly applicant_username: string;
            /** Format: email */
            readonly applicant_email: string;
            status?: components["schemas"]["StatusEnum"];
            readonly status_display: string;
            readonly cover_note: string;
            /** Format: double */
            readonly match_score: number | null;
            readonly resume_url: string | null;
            readonly resume_skills: string[];
            /** Format: date-time */
            readonly applied_at: string;
            /** Format: date-time */
            readonly status_changed_at: string;
        };
        /** @description A seeker's view of their own application. */
        Application: {
            readonly id: number;
            readonly job: components["schemas"]["JobSummary"];
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_display: string;
            readonly cover_note: string;
            /** Format: double */
            readonly match_score: number | null;
            /** Format: date-time */
            readonly applied_at: string;
            /** Format: date-time */
            readonly status_changed_at: string;
        };
        ApplicationCreate: {
            job: number;
            cover_note?: string;
        };
        ApplicationCreateRequest: {
            job: number;
            cover_note?: string;
        };
        AtsReport: {
            score: number;
            verdict: string;
            keyword_score: number;
            quality_score: number;
            matched_skills: string[];
            missing_skills: components["schemas"]["SkillGap"][];
            matched_education: string[];
            required_years: number | null;
            /** Format: double */
            keyword_density: number;
            word_count: number;
            checks: components["schemas"]["Check"][];
            suggestions: string[];
        };
        AtsRequestRequest: {
            /** @description Paste the full job description, including requirements. */
            job_description: string;
            /** @description Defaults to your primary resume. */
            resume_id?: number;
        };
        /**
         * @description Response shape shared by register and login.
         *
         *     Declared explicitly so the generated OpenAPI schema -- and therefore the
         *     frontend's generated types -- match what these views actually return.
         */
        AuthTokenResponse: {
            readonly access: string;
            readonly refresh: string;
            readonly user: components["schemas"]["User"];
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        Check: {
            id: string;
            label: string;
            passed: boolean;
            severity: components["schemas"]["SeverityEnum"];
            detail: string;
        };
        Health: {
            status: string;
            database: string;
        };
        Job: {
            readonly id: number;
            job_title: string;
            company_name: string;
            location: string;
            is_remote?: boolean;
            job_type?: components["schemas"]["JobTypeEnum"];
            readonly job_type_display: string;
            /** Format: decimal */
            salary_min?: string | null;
            /** Format: decimal */
            salary_max?: string | null;
            salary_currency?: string;
            job_description: string;
            job_requirements?: string;
            readonly skills: string[];
            /** Format: date-time */
            readonly posted_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            expiry_time?: string | null;
            is_active?: boolean;
            readonly is_open: boolean;
            readonly recruiter: number;
            readonly recruiter_name: string;
            readonly application_count: number;
            readonly has_applied: boolean;
        };
        JobRequest: {
            job_title: string;
            company_name: string;
            location: string;
            is_remote?: boolean;
            job_type?: components["schemas"]["JobTypeEnum"];
            /** Format: decimal */
            salary_min?: string | null;
            /** Format: decimal */
            salary_max?: string | null;
            salary_currency?: string;
            job_description: string;
            job_requirements?: string;
            /** Format: date-time */
            expiry_time?: string | null;
            is_active?: boolean;
        };
        /** @description Compact form used inside recommendations and application listings. */
        JobSummary: {
            readonly id: number;
            job_title: string;
            company_name: string;
            location: string;
            is_remote?: boolean;
            job_type?: components["schemas"]["JobTypeEnum"];
            readonly job_type_display: string;
            /** Format: decimal */
            salary_min?: string | null;
            /** Format: decimal */
            salary_max?: string | null;
            salary_currency?: string;
            /** Format: date-time */
            readonly posted_at: string;
            /** Format: date-time */
            expiry_time?: string | null;
        };
        /** @description Compact form used inside recommendations and application listings. */
        JobSummaryRequest: {
            job_title: string;
            company_name: string;
            location: string;
            is_remote?: boolean;
            job_type?: components["schemas"]["JobTypeEnum"];
            /** Format: decimal */
            salary_min?: string | null;
            /** Format: decimal */
            salary_max?: string | null;
            salary_currency?: string;
            /** Format: date-time */
            expiry_time?: string | null;
        };
        /**
         * @description * `INTERN` - Internship
         *     * `FULL_TIME` - Full-Time
         *     * `PART_TIME` - Part-Time
         *     * `TEMPORARY` - Temporary
         *     * `CONTRACT` - Contract
         * @enum {string}
         */
        JobTypeEnum: "INTERN" | "FULL_TIME" | "PART_TIME" | "TEMPORARY" | "CONTRACT";
        /**
         * @description Adds the user object to the token response.
         *
         *     Saves the client a round trip, and means the frontend never has to hold on
         *     to credentials to identify the current user.
         */
        LoginRequest: {
            username: string;
            password: string;
        };
        LogoutRequest: {
            refresh: string;
        };
        PaginatedApplicantList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Applicant"][];
        };
        PaginatedApplicationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Application"][];
        };
        PaginatedJobList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Job"][];
        };
        PaginatedResumeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Resume"][];
        };
        PatchedJobRequest: {
            job_title?: string;
            company_name?: string;
            location?: string;
            is_remote?: boolean;
            job_type?: components["schemas"]["JobTypeEnum"];
            /** Format: decimal */
            salary_min?: string | null;
            /** Format: decimal */
            salary_max?: string | null;
            salary_currency?: string;
            job_description?: string;
            job_requirements?: string;
            /** Format: date-time */
            expiry_time?: string | null;
            is_active?: boolean;
        };
        PatchedUpdateProfileRequest: {
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email?: string;
            recruiter_profile?: components["schemas"]["RecruiterProfileRequest"];
        };
        Recommendation: {
            readonly job: components["schemas"]["JobSummary"];
            /** Format: double */
            readonly score: number;
            readonly match_percentage: number;
            readonly matched_skills: string[];
            readonly missing_skills: string[];
            readonly has_applied: boolean;
        };
        RecruiterProfile: {
            company_name: string;
            /** Format: uri */
            company_website?: string;
            company_location?: string;
            about?: string;
        };
        RecruiterProfileRequest: {
            company_name: string;
            /** Format: uri */
            company_website?: string;
            company_location?: string;
            about?: string;
        };
        RegisterRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirm: string;
            first_name?: string;
            last_name?: string;
            /** @default SEEKER */
            role: components["schemas"]["RoleEnum"];
            /** @description Required when registering as a recruiter. */
            company_name?: string;
        };
        Resume: {
            readonly id: number;
            readonly original_filename: string;
            readonly content_type: string;
            readonly size_bytes: number;
            readonly extracted_skills: string[];
            readonly extracted_education: string[];
            readonly skill_count: number;
            readonly is_primary: boolean;
            readonly is_parsed: boolean;
            readonly parse_error: string;
            /** Format: date-time */
            readonly parsed_at: string | null;
            /** Format: date-time */
            readonly uploaded_at: string;
            readonly download_url: string;
        };
        ResumeUploadRequest: {
            /** Format: binary */
            file: string;
        };
        /**
         * @description * `SEEKER` - Job seeker
         *     * `RECRUITER` - Recruiter
         * @enum {string}
         */
        RoleEnum: "SEEKER" | "RECRUITER";
        /**
         * @description * `critical` - critical
         *     * `warning` - warning
         *     * `info` - info
         * @enum {string}
         */
        SeverityEnum: "critical" | "warning" | "info";
        SkillGap: {
            skill: string;
            /** Format: double */
            importance: number;
        };
        /**
         * @description * `SUBMITTED` - Submitted
         *     * `IN_REVIEW` - In review
         *     * `SHORTLISTED` - Shortlisted
         *     * `REJECTED` - Rejected
         *     * `ACCEPTED` - Accepted
         * @enum {string}
         */
        StatusEnum: "SUBMITTED" | "IN_REVIEW" | "SHORTLISTED" | "REJECTED" | "ACCEPTED";
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        UpdateProfile: {
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email: string;
            recruiter_profile?: components["schemas"]["RecruiterProfile"];
        };
        UpdateProfileRequest: {
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email: string;
            recruiter_profile?: components["schemas"]["RecruiterProfileRequest"];
        };
        User: {
            readonly id: number;
            username: string;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            readonly full_name: string;
            readonly role: components["schemas"]["RoleEnum"];
            /** Format: date-time */
            readonly date_joined: string;
            readonly recruiter_profile: components["schemas"]["RecruiterProfile"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_list: {
        parameters: {
            query?: {
                job?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `SUBMITTED` - Submitted
                 *     * `IN_REVIEW` - In review
                 *     * `SHORTLISTED` - Shortlisted
                 *     * `REJECTED` - Rejected
                 *     * `ACCEPTED` - Accepted
                 */
                status?: "ACCEPTED" | "IN_REVIEW" | "REJECTED" | "SHORTLISTED" | "SUBMITTED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedApplicationList"];
                };
            };
        };
    };
    applications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApplicationCreateRequest"];
                "multipart/form-data": components["schemas"]["ApplicationCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationCreate"];
                };
            };
        };
    };
    applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Job application. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Job application. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    ats_report_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtsRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AtsRequestRequest"];
                "multipart/form-data": components["schemas"]["AtsRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtsReport"];
                };
            };
        };
    };
    auth_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Refresh token blacklisted */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateProfileRequest"];
                "multipart/form-data": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateProfile"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateProfile"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    auth_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    jobs_list: {
        parameters: {
            query?: {
                company_name?: string;
                is_remote?: boolean;
                /**
                 * @description * `INTERN` - Internship
                 *     * `FULL_TIME` - Full-Time
                 *     * `PART_TIME` - Part-Time
                 *     * `TEMPORARY` - Temporary
                 *     * `CONTRACT` - Contract
                 */
                job_type?: ("CONTRACT" | "FULL_TIME" | "INTERN" | "PART_TIME" | "TEMPORARY")[];
                location?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                posted_after?: string;
                salary_max?: number;
                salary_min?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobList"];
                };
            };
        };
    };
    jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["JobRequest"];
                "multipart/form-data": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    jobs_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["JobRequest"];
                "multipart/form-data": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    jobs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    jobs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedJobRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedJobRequest"];
                "multipart/form-data": components["schemas"]["PatchedJobRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    jobs_applicants_list: {
        parameters: {
            query?: {
                company_name?: string;
                is_remote?: boolean;
                /**
                 * @description * `INTERN` - Internship
                 *     * `FULL_TIME` - Full-Time
                 *     * `PART_TIME` - Part-Time
                 *     * `TEMPORARY` - Temporary
                 *     * `CONTRACT` - Contract
                 */
                job_type?: ("CONTRACT" | "FULL_TIME" | "INTERN" | "PART_TIME" | "TEMPORARY")[];
                location?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                posted_after?: string;
                salary_max?: number;
                salary_min?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedApplicantList"];
                };
            };
        };
    };
    recommendations_list: {
        parameters: {
            query?: {
                /** @description Maximum results (1-50). Default 10. */
                limit?: number;
                /** @description Score floor, 0-1. Default 0. */
                min_score?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"][];
                };
            };
        };
    };
    resumes_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResumeList"];
                };
            };
        };
    };
    resumes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this resume. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
    resumes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this resume. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resumes_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this resume. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resume file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resumes_set_primary_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this resume. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
    resumes_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ResumeUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
}
